name: learn-github-actions
run-name: Docker image
on: [push]
jobs:
  create-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag sample-image:$(date +%s)
